map/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('panel.urls')),
    re_path(r'^download/(?P<path>.*)$',serve,{'documnet_root':settings.STATIC_ROOT})
]

panel/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib import admin
from django.urls import path, include

urlpatterns=[
    path('', views.home, name='home'),
    path('SubmitInformation', views.Submit_Information_View, name='Submit_Information_Path'),
    path('Cartable', views.Cartable, name='Cartable_Path'),
    path('Cartable/<int:id>/', views.Cartable_Details, name='Cartable_Details_Path'),
]

panel/models.py
import uuid
import os
from django.db import models
from django_jalali.db import models as jmodels
from datetime import datetime

def files_upload_location(instance, filename):
    filebase, extension = filename.split('.')
    filebase = uuid.uuid4().urn
    return 'Storage/Files/{filebase}.{ext}'.format(filebase=filebase, ext=extension)

def shp_upload_location(instance, filename):
    filebase, extension = filename.split('.')
    filebase = uuid.uuid4().urn
    return 'Storage/Shp/{filebase}.{ext}'.format(filebase=filebase, ext=extension)

class Submit_Information_Model(models.Model):
    project_id = models.AutoField(primary_key=True)
    project_employer = models.CharField(max_length=500, null=True, blank=True)
    project_manager = models.CharField(max_length=500, null=True, blank=True)
    date_letter = models.DateField(default=datetime.now, null=True, blank=True)
    letter_number = models.CharField(max_length=500, null=True, blank=True)
    recipiant = models.CharField(max_length=500, null=True, blank=True)
    coordinator = models.CharField(max_length=500, null=True, blank=True)
    description_letter = models.CharField(max_length=500, null=True, blank=True)
    phone = models.CharField(max_length=500, null=True, blank=True)
    state = models.CharField(max_length=500, null=True, blank=True)
    date_deposit = models.DateField(default=datetime.now, null=True, blank=True)
    description = models.CharField(max_length=500, null=True, blank=True)
    amount_deposit = models.IntegerField(null=True, blank=True)
    tracking_code = models.CharField(max_length=500, null=True, blank=True)
    status = models.CharField(max_length=500, null=True, blank=True)
    shp_file = models.FileField(upload_to=shp_upload_location, null=True, blank=True)
    doc_file = models.FileField(upload_to=files_upload_location, null=True, blank=True)
    add_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Submit_Information'

    def __str__(self):
        template = '{0.project_id} {0.project_employer} {0.project_manager}'
        return template.format(self)

panel/forms.py
from django.forms import ModelForm
from .models import Submit_Information_Model
from jalali_date.fields import JalaliDateField, SplitJalaliDateTimeField
from jalali_date.widgets import AdminJalaliDateWidget, AdminSplitJalaliDateTime
from django import forms

class Submit_Information_Form(forms.ModelForm):
    description_letter = forms.CharField(widget=forms.Textarea(attrs={"rows":8}), required=False)
    description = forms.CharField(widget=forms.Textarea(attrs={"rows":8}), required=False)
    class Meta:
        model = Submit_Information_Model
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(Submit_Information_Form, self).__init__(*args, **kwargs)
        self.fields['date_letter'] = JalaliDateField(label=('date_letter'),
            widget=AdminJalaliDateWidget
        )
        self.fields['date_deposit'] = JalaliDateField(label=('date_deposit'), 
            widget=AdminJalaliDateWidget
        )
        self.fields['date_letter'].required=False
        self.fields['date_deposit'].required=False
        # self.fields['description_letter', 'description', 'date_letter', 'date_deposit'].required = False

panel/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Submit_Information_Form
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import Submit_Information_Model
from django.utils.datastructures import MultiValueDictKeyError
from django.db.models import CharField
from django.db.models import  Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from jalali_date import datetime2jalali, date2jalali
import jdatetime
import os


def Submit_Information_View(request):
    global form
    if request.method == "POST":
        SubmitInformation = Submit_Information_Form(request.POST or None, request.FILES or None)
        if SubmitInformation.is_valid():
            project_employer = request.POST.get('project_employer', False)
            project_manager = request.POST.get('project_manager', False)
            date_letter = request.POST.get('date_letter', False)
            letter_number = request.POST.get('letter_number', False)
            recipiant = request.POST.get('recipiant', False)
            coordinator = request.POST.get('coordinator', False)
            description_letter = request.POST.get('description_letter', False)
            phone = request.POST.get('phone', False)
            state = request.POST.get('state', False)
            date_deposit = request.POST.get('date_deposit', False)
            description = request.POST.get('description', False)
            amount_deposit = request.POST.get('amount_deposit', False)
            tracking_code = request.POST.get('tracking_code', False)
            status = request.POST.get('status', False)
            try:
                shp_file = request.POST['shp_file']
            except MultiValueDictKeyError:
                shp_file = False

            try:
                doc_file = request.POST['doc_file']
            except MultiValueDictKeyError:
                doc_file = False

            SubmitInformation.project_employer = project_employer
            SubmitInformation.project_manager = project_manager
            SubmitInformation.date_letter = date_letter
            SubmitInformation.letter_number = letter_number
            SubmitInformation.recipiant = recipiant
            SubmitInformation.coordinator = coordinator
            SubmitInformation.description_letter = description_letter
            SubmitInformation.phone = phone
            SubmitInformation.state = state
            SubmitInformation.date_deposit = date_deposit
            SubmitInformation.description = description
            SubmitInformation.amount_deposit = amount_deposit
            SubmitInformation.tracking_code = tracking_code
            SubmitInformation.status = status
            SubmitInformation.shp_file = shp_file
            SubmitInformation.doc_file = doc_file

            SubmitInformation.save()
            messages.success(request, 'فرم با موفقیت ثبت شد')
            return render(request, 'Submit_Information.html', {'form': Submit_Information_Form(request.GET)})
        else:
            messages.error(request, 'مشکلی در ثبت فرم وجود دارد')
            messages.error(request, SubmitInformation.errors)
    else:
        form = Submit_Information_Form(use_required_attribute=False)
    return render(request, 'Submit_Information.html', {'form': form})


def home(request):
    return render(request, 'welcome.html')

def Cartable(request):
    if 'q' in request.GET:
        q = request.GET['q']
        multiple_q = Q(Q(project_employer__icontains=q) | Q(project_manager__icontains=q) | Q(date_letter__icontains=q) |
                        Q(letter_number__icontains=q) | Q(recipiant__icontains=q) | Q(coordinator__icontains=q) |
                        Q(description_letter__icontains=q) | Q(phone__icontains=q) | Q(state__icontains=q) | 
                        Q(date_deposit__icontains=q) | Q(description__icontains=q) | Q(amount_deposit__icontains=q) | 
                        Q(tracking_code__icontains=q) | Q(status__icontains=q)
                        )

        Cartables = Submit_Information_Model.objects.filter(multiple_q).order_by('-add_time')
    else:
        Cartables = Submit_Information_Model.objects.all().order_by('-add_time')
    default_page = 1
    page = request.GET.get('page', default_page)
    items_per_page = 15
    paginator = Paginator(Cartables, items_per_page)
    try:
        Cartables = paginator.page(page)
    except PageNotAnInteger:
        Cartables = paginator.page(default_page)
    except EmptyPage:
        Cartables = paginator.page(paginator.num_pages)
    return render(request, 'Cartable.html', {'Cartables': Cartables})
    
from django.shortcuts import (get_object_or_404,
                              render,
                              HttpResponseRedirect,
                              HttpResponse)
def Cartable_Details(request, id):
    Cartable = Submit_Information_Model.objects.get(pk = id)
    form = Submit_Information_Form(request.POST or None, instance=Cartable)
    if 'update' in request.POST:
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/Cartable")
    elif 'delete' in request.POST:
        obj = get_object_or_404(Submit_Information_Model, project_id = id)
        obj.delete()
        return HttpResponseRedirect("/Cartable")
    return render(request, 'Cartable_Details.html', {'form':form})
from django.conf import settings
from django.http import Http404

def Download(requset, path):
    Cartables = Submit_Information_Model.objects.all()
    file_path=os.path.join(settings.STATIC_ROOT,path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(),content_type='application/doc_file')
            response['Content-Disposition']='inline;filename='+os.path(file_path)
            return render(response, 'Cartable.html')
    return Http404

panel/templates/Cartable_Details.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load jalali_tags %}
{% block content %}
<html lang="fa" dir="rtl">
    <head>
        <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
		<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
        <style>

            h3{
            font-family: Calibri; 
            font-size: 25pt;         
            font-style: normal; 
            font-weight: bold; 
            color:#000000;
            text-align: center; 
            text-decoration: underline
            }

            table{
                width: 60%;
                opacity: 0.96;
            font-family: Calibri; 
            color:rgb(0, 0, 0); 
            font-size: 11pt; 
            font-style: normal;
            font-weight: bold;
            background-color: silver; 
            border-collapse: collapse; 
            border: 2px solid rgb(212, 214, 183)
            }

            table.inner{
            border: 0px
            }
            /* .post-form input{
                display: flex;
            } */

        </style>
    </head>

    <body dir="rtl">
        <form method="post" class="post-form" enctype="multipart/form-data">
            
            {% csrf_token %}
            <table align="center" cellpadding = "10" style="display: flex; padding: 60px; margin-top: 2%; width: 1100px;">
                <tbody style="margin: auto;">
                    <tr>
                        <td>
                            <h3 style="text-align: justify; display: flex; font-family: IranSansBold;">فرم ثبت اطلاعات</h3>    
                        </td>
                    </tr>

                    <tr style="font-family: IranSans;">
                        <td style="display: flex; width: 20rem; padding-right: 5rem;">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert {{ message.tags }}" role="alert" style="display: flex; width: 20rem;">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </td>
                    </tr>

                    <tr style="font-family: IranSans;">
                        <div class="row">
                            <td style="width: 20rem;">
                                <label for="id_project_employer">کارفرمای پروژه</label>
                                {{ form.project_employer|add_class:"form-control" }}
                            </td>
                            <td style="width: 25rem; padding-right: 5rem;">
                                <label for="id_project_manager">مجری پروژه</label>
                                {{ form.project_manager|add_class:"form-control" }}
                            </td>
                        </div>
                    </tr>
        
                    <tr style="font-family: IranSans;">
                        <td>
                            <div  class="col-auto my-1">
                                <label class="mr-sm-2" for="id_day_letter">تاریخ نامه</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                {{ form.date_letter }}
                            </div>    
                        </td>
        
                        <td style="display: flex; padding-right: 5rem; width: 178%;">
                            <div class="form-group col-md-6" style="display: felx;">
                                <label for="id_letter_number">شماره نامه</label>
                                {{ form.letter_number|add_class:"form-control" }}
                            </div>
                        </td>
                    </tr>
        
                    <tr style="font-family: IranSans;">
                        <div class="row">
                            <td style="width: 20rem;">
                                <label for="id_recipiant">گیرنده نامه</label>
                                {{ form.recipiant|add_class:"form-control" }}
                            </td>
                            <td style="width: 25rem; padding-right: 5rem;">
                                <label for="id_coordinator">هماهنگ کننده</label>
                                {{ form.coordinator|add_class:"form-control" }}
                            </td>
                        </div>
                    </tr>
                    

                    <tr>
                        <td>
                            <br/>
                        </td>
                    </tr>

                    
                    <tr style="font-family: IranSans;">
                        <div class="row">
                            <td>
                                <div class="form-outline">
                                    <label class="form-label" for="id_description_letter">موضوع یا شرح نامه</label>
                                    {{ form.description_letter|add_class:"form-control"|attr:"rows:8" }}
                                </div>
                            </td>

                            <td style="display: flex; padding-right: 5rem; width: 178%;">
                                <div class="form-group col-md-6" style="display: felx;">
                                    <label for="id_phone">شماره تماس</label>
                                    {{ form.phone|add_class:"form-control" }}
                                </div>
                            </td>

                            <td style="display: flex; padding-right: 5rem;">
                                <div class="form-group col-md-6" style="display: felx;">
                                    <label for="id_state">استان</label>
                                    {{ form.state|add_class:"form-control" }}
                                    <br/><br/>
                                </div>
                            </td>

                            

                            <td style="display: flex; padding-right: 5rem;">
                                <div  class="col-auto my-1">
                                    <label class="mr-sm-2" for="id_deposit">تاریخ واریز</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                    {{ form.date_deposit }}
                                </div>    
                            </td>
                        </div>
                    </tr>

                    <tr>
                        <td>
                            <br/>
                        </td>
                    </tr>

                    <tr style="font-family: IranSans;">
                        <div class="row">
                            <td>
                                <div class="form-outline">
                                    <label class="form-label" for="id_description">توضیحات</label>
                                    {{ form.description|add_class:"form-control" }}
                                </div>
                            </td>
                            <td style="display: flex; padding-right: 5rem;">
                                <div class="form-group col-md-6" style="display: felx;">
                                    <label for="id_amount_deposit">مبلغ واریزی</label>
                                    {{ form.amount_deposit|add_class:"form-control" }}
                                </div>
                            </td>
                            <td style="display: flex; padding-right: 5rem;">
                                <div class="form-group col-md-6" style="display: felx;">
                                    <label for="id_tracking_code">کد پیگیری</label>
                                    {{ form.tracking_code|add_class:"form-control" }}
                                </div>
                            </td>
                            <td style="display: flex; padding-right: 5rem;">
                                <div class="form-group col-md-6" style="display: felx;">
                                    <label for="id_status">وضعیت</label>
                                    {{ form.status|add_class:"form-control" }}
                                </div>
                            </td>
                        </div>
                    </tr>


                    <tr class="row">
                        <td>
                            <div>
                                <label for="id_shp_file" class="form-label">فایل با فرمت shp</label>
                                <input name="shp_file" class="form-control form-control-lg" id="id_shp_file" type="file">
                            </div>
                            <div>
                                <label for="id_doc_file" class="form-label">فایل های ذخیره</label>
                                <input name="doc_file" class="form-control form-control-lg" id="id_doc_file" type="file">
                            </div>
                        </td>
                    </tr>
        
                    <tr>
                        <td>
                            <br/><br/>
                        </td>
                    </tr>
        
                    <tr style="font-family: IranSans;">
                        <div class="row">
                            <td>
                                <button type="submit" value="Submit" class="btn btn-primary btn-lg active" data-toggle="button" aria-pressed="false" autocomplete="off" style="width: 458%; margin-right:-13%" name="update"> ثبت </button>
                            </td>
                            <td>
                                <button type="reset" class="btn btn-secondary btn-lg active" data-toggle="button" aria-pressed="false" autocomplete="off" style="width: 355%; margin-right:251%"> بازنشانی </button>
                            </td>
                        </div>
                    </tr>
                    <tr style="font-family: IranSans;">
                        <div class="row">
                            <td>
                                <button type="submit" class="btn btn-danger btn-lg active" data-toggle="button" aria-pressed="false" autocomplete="off" style="width: 942%;margin-right:-14%" name="delete"> حذف</button>
                            </td>
                        </div>
                    </tr>
                </tbody>
            </table>
        </form>
    </body>
</html>
{% endblock %}

panel/templates/Submit_Information.html
{% extends 'base.html' %}
{% block content %}
<html lang="fa" dir="rtl">
    <head>
        <style>

            h3{
            font-family: Calibri; 
            font-size: 25pt;         
            font-style: normal; 
            font-weight: bold; 
            color:#000000;
            text-align: center; 
            text-decoration: underline
            }

            table{
                width: 60%;
                opacity: 0.96;
            font-family: Calibri; 
            color:rgb(0, 0, 0); 
            font-size: 11pt; 
            font-style: normal;
            font-weight: bold;
            background-color: silver; 
            border-collapse: collapse; 
            border: 2px solid rgb(212, 214, 183)
            }

            table.inner{
            border: 0px
            }

        </style>
    </head>
 
    <body dir="rtl">
        <form method="post" class="post-form" enctype="multipart/form-data">
            {% csrf_token %}
            <table align="center" cellpadding = "10" style="display: flex; padding: 60px; margin-top: 2%; width: 1100px;">
                <tbody style="margin: auto;">
                    <tr>
                        <td>
                            <h3 style="text-align: justify; display: flex; font-family: IranSansBold;">فرم ثبت اطلاعات</h3>    
                        </td>
                    </tr>

                    <tr style="font-family: IranSans;">
                        <td style="display: flex; width: 20rem; padding-right: 5rem;">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert {{ message.tags }}" role="alert" style="display: flex; width: 20rem;">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </td>
                    </tr>

                    <tr style="font-family: IranSans;">
                        <div class="row">
                            <td style="width: 20rem;">
                                <label for="project_employer">کارفرمای پروژه</label>
                                <input name="project_employer" type="text" class="form-control" id="project_employer" placeholder="کارفرمای پروژه">
                            </td>
                            <td style="width: 25rem; padding-right: 5rem;">
                                <label for="project_manager">مجری پروژه</label>
                                <input name="project_manager" type="text" class="form-control" id="project_manager" placeholder="مجری پروژه">
                            </td>
                        </div>
                    </tr>
        
                    <tr style="font-family: IranSans;">
                        <td>
                            <div  class="col-auto my-1">
                                <label class="mr-sm-2" for="id_date_letter">تاریخ نامه</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                {{ form.date_letter }}
                            </div>    
                        </td>
        
                        <td style="display: flex; padding-right: 5rem; width: 178%;">
                            <div class="form-group col-md-6" style="display: felx;">
                                <label for="letter_number">شماره نامه</label>
                                <input name="letter_number" type="text" class="form-control" id="letter_number" placeholder="شماره نامه">
                            </div>
                        </td>
                    </tr>
        
                    <tr style="font-family: IranSans;">
                        <div class="row">
                            <td style="width: 20rem;">
                                <label for="recipiant">گیرنده نامه</label>
                                <input name="recipiant" type="text" class="form-control" id="recipiant" placeholder="گیرنده نامه">
                            </td>
                            <td style="width: 25rem; padding-right: 5rem;">
                                <label for="coordinator">هماهنگ کننده</label>
                                <input name="coordinator" type="text" class="form-control" id="coordinator" placeholder="هماهنگ کننده">
                            </td>
                        </div>
                    </tr>
                    

                    <tr>
                        <td>
                            <br/>
                        </td>
                    </tr>

                    
                    <tr style="font-family: IranSans;">
                        <div class="row">
                            <td>
                                <div class="form-outline">
                                    <label class="form-label" for="description_letter">موضوع یا شرح نامه</label>
                                    <textarea name="description_letter" class="form-control" id="description_letter" rows="8"></textarea>
                                </div>
                            </td>

                            <td style="display: flex; padding-right: 5rem; width: 178%;">
                                <div class="form-group col-md-6" style="display: felx;">
                                    <label for="phone">شماره تماس</label>
                                    <input name="phone" type="text" class="form-control" id="phone" placeholder="تلفن">
                                </div>
                            </td>

                            <td style="display: flex; padding-right: 5rem;">
                                <div class="form-group col-md-6" style="display: felx;">
                                    <label for="state">استان</label>
                                    <input name="state" type="text" class="form-control" id="state" placeholder="استان">
                                    <br/><br/>
                                </div>
                            </td>

                            

                            <td style="display: flex; padding-right: 5rem;">
                                <div  class="col-auto my-1">
                                    <label class="mr-sm-2" for="id_deposit">تاریخ واریز</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                    {{ form.date_deposit }}
                                </div>    
                            </td>
                        </div>
                    </tr>

                    <tr>
                        <td>
                            <br/>
                        </td>
                    </tr>

                    <tr style="font-family: IranSans;">
                        <div class="row">
                            <td>
                                <div class="form-outline">
                                    <label class="form-label" for="description">توضیحات</label>
                                    <textarea name="description" class="form-control" id="description" rows="8"></textarea>
                                </div>
                            </td>
                            <td style="display: flex; padding-right: 5rem;">
                                <div class="form-group col-md-6" style="display: felx;">
                                    <label for="amount_deposit">مبلغ واریزی</label>
                                    <input name="amount_deposit" type="text" class="form-control" id="amount_deposit" placeholder="ریال">
                                </div>
                            </td>
                            <td style="display: flex; padding-right: 5rem;">
                                <div class="form-group col-md-6" style="display: felx;">
                                    <label for="tracking_code">کد پیگیری</label>
                                    <input name="tracking_code" type="text" class="form-control" id="tracking_code" placeholder="کد پیگیری">
                                </div>
                            </td>
                            <td style="display: flex; padding-right: 5rem;">
                                <div class="form-group col-md-6" style="display: felx;">
                                    <label for="status">وضعیت</label>
                                    <input name="status" type="text" class="form-control" id="status" placeholder="وضعیت">
                                </div>
                            </td>
                        </div>
                    </tr>


                    <tr class="row">
                        <td>
                            <div>
                                <label for="id_shp_file" class="form-label">فایل با فرمت shp</label>
                                <input name="shp_file" class="form-control form-control-lg" id="id_shp_file" type="file">
                            </div>
                            <div>
                                <label for="id_doc_file" class="form-label">فایل های ذخیره</label>
                                <input name="doc_file" class="form-control form-control-lg" id="id_doc_file" type="file">
                            </div>
                        </td>
                    </tr>
        
                    <tr>
                        <td>
                            <br/><br/>
                        </td>
                    </tr>
        
                    <tr style="font-family: IranSans;">
                        <div class="row">
                            <td>
                                <button type="submit" value="Submit" class="btn btn-primary btn-lg active" data-toggle="button" aria-pressed="false" autocomplete="off" style="width: 522%; margin-right:-13%" name="update"> ثبت </button>
                            </td>
                            <td>
                                <button type="reset" class="btn btn-secondary btn-lg active" data-toggle="button" aria-pressed="false" autocomplete="off" style="width: 340%; margin-right:270%"> بازنشانی </button>
                            </td>
                        </div>
                    </tr>
                </tbody>
            </table>
        </form>
    </body>
</html>
{% endblock %}

panel/templates/welcome.html
{% extends 'base.html' %}
{% block content %}
<label style="margin-top: 15%; font-family: IranNastaliq; font-size: 121px; text-align: center; display: inherit; color: darkblue; font-weight: bold;">
به سامانه نقشه خوش آمدید
</label>
{% endblock %}